In [3]:
import pandas as pd
import numpy as np

In [ ]:
from google.collab import files
uploaded=files.upload("")

### Persisting Data using Google Drive
By mounting Google Drive, you can save your dataset permanently so it remains available even after the runtime terminates.

In [7]:
from google.colab import drive
import shutil
import os

# Mount Google Drive
drive.mount('/content/drive')

# Create a folder in your Drive for datasets if it doesn't exist
destination_dir = '/content/drive/MyDrive/Colab_Datasets'
os.makedirs(destination_dir, exist_ok=True)

# Copy the dataset from local runtime to Google Drive
source_path = '/content/marketing_campaign.csv'
dest_path = os.path.join(destination_dir, 'marketing_campaign.csv')

if os.path.exists(source_path):
    shutil.copy(source_path, dest_path)
    print(f'File successfully saved to Google Drive at: {dest_path}')
else:
    print('Source file not found. Please make sure marketing_campaign.csv is uploaded.')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
File successfully saved to Google Drive at: /content/drive/MyDrive/Colab_Datasets/marketing_campaign.csv

### Loading the dataset from Google Drive
In your future sessions, you can easily load the dataset using the following code after mounting Google Drive:

In [8]:
# Load the saved CSV directly into a pandas DataFrame
df = pd.read_csv('/content/drive/MyDrive/Colab_Datasets/marketing_campaign.csv', sep=None, engine='python')
display(df.head())

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,11,...,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,173,...,5,0,0,0,0,0,0,3,11,0

In [9]:
# Mount Google Drive and load the persistent dataset directly
from google.colab import drive
import pandas as pd

drive.mount('/content/drive')

# Load the dataset from your permanent Drive folder
file_path = '/content/drive/MyDrive/Colab_Datasets/marketing_campaign.csv'
df = pd.read_csv(file_path, sep=None, engine='python')
display(df.head())

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,11,...,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,173,...,5,0,0,0,0,0,0,3,11,0

In [10]:

df = pd.read_csv("marketing_campaign.csv", sep="\t")
df.head()

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,11,...,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,173,...,5,0,0,0,0,0,0,3,11,0

In [11]:
print("dataset shape:",df.shape)

dataset shape: (2240, 29)

In [12]:
print("Total rows:", df.shape[0])
print("Total columns:", df.shape[1])

Total rows: 2240
Total columns: 29

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 29 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   2240 non-null   int64
 1   Year_Birth           2240 non-null   int64
 2   Education            2240 non-null   object
 3   Marital_Status       2240 non-null   object
 4   Income               2216 non-null   float64
 5   Kidhome              2240 non-null   int64
 6   Teenhome             2240 non-null   int64
 7   Dt_Customer          2240 non-null   object
 8   Recency              2240 non-null   int64
 9   MntWines             2240 non-null   int64
 10  MntFruits            2240 non-null   int64
 11  MntMeatProducts      2240 non-null   int64
 12  MntFishProducts      2240 non-null   int64
 13  MntSweetProducts     2240 non-null   int64
 14  MntGoldProds         2240 non-null   int64
 15  NumDealsPurchases    2240 non-null   int64
 16  NumWebPurchases      2240 non-null   int64
 17  NumCatalogPurchases  2240 non-null   int64
 18  NumStorePurchases    2240 non-null   int64
 19  NumWebVisitsMonth    2240 non-null   int64
 20  AcceptedCmp3         2240 non-null   int64
 21  AcceptedCmp4         2240 non-null   int64
 22  AcceptedCmp5         2240 non-null   int64
 23  AcceptedCmp1         2240 non-null   int64
 24  AcceptedCmp2         2240 non-null   int64
 25  Complain             2240 non-null   int64
 26  Z_CostContact        2240 non-null   int64
 27  Z_Revenue            2240 non-null   int64
 28  Response             2240 non-null   int64
dtypes: float64(1), int64(25), object(3)
memory usage: 507.6+ KB

In [14]:
print("missing values in each colmn")
print(df.isnull().sum())

missing values in each colmn
ID                      0
Year_Birth              0
Education               0
Marital_Status          0
Income                 24
Kidhome                 0
Teenhome                0
Dt_Customer             0
Recency                 0
MntWines                0
MntFruits               0
MntMeatProducts         0
MntFishProducts         0
MntSweetProducts        0
MntGoldProds            0
NumDealsPurchases       0
NumWebPurchases         0
NumCatalogPurchases     0
NumStorePurchases       0
NumWebVisitsMonth       0
AcceptedCmp3            0
AcceptedCmp4            0
AcceptedCmp5            0
AcceptedCmp1            0
AcceptedCmp2            0
Complain                0
Z_CostContact           0
Z_Revenue               0
Response                0
dtype: int64

In [15]:


missing_income = df[df["Income"].isnull()]

print("Number of rows with missing Income:",
      len(missing_income))

display(missing_income.head(10))

Number of rows with missing Income: 24

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
10,1994,1983,Graduation,Married,NaN,1,0,15-11-2013,11,5,...,7,0,0,0,0,0,0,3,11,0
27,5255,1986,Graduation,Single,NaN,1,0,20-02-2013,19,5,...,1,0,0,0,0,0,0,3,11,0
43,7281,1959,PhD,Single,NaN,0,0,05-11-2013,80,81,...,2,0,0,0,0,0,0,3,11,0
48,7244,1951,Graduation,Single,NaN,2,1,01-01-2014,96,48,...,6,0,0,0,0,0,0,3,11,0
58,8557,1982,Graduation,Single,NaN,1,0,17-06-2013,57,11,...,6,0,0,0,0,0,0,3,11,0
71,10629,1973,2n Cycle,Married,NaN,1,0,14-09-2012,25,25,...,8,0,0,0,0,0,0,3,11,0
90,8996,1957,PhD,Married,NaN,2,1,19-11-2012,4,230,...,9,0,0,0,0,0,0,3,11,0
91,9235,1957,Graduation,Single,NaN,1,1,27-05-2014,45,7,...,7,0,0,0,0,0,0,3,11,0
92,5798,1973,Master,Together,NaN,0,0,23-11-2013,87,445,...,1,0,0,0,0,0,0,3,11,0
128,8268,1961,PhD,Married,NaN,0,1,11-07-2013,23,352,...,6,0,0,0,0,0,0,3,11,0

In [16]:

print(df["Income"].describe())
print("Median income:", df["Income"].median())

count      2216.000000
mean      52247.251354
std       25173.076661
min        1730.000000
25%       35303.000000
50%       51381.500000
75%       68522.000000
max      666666.000000
Name: Income, dtype: float64
Median income: 51381.5

In [17]:


missing_before = df["Income"].isnull().sum()
median_income = df["Income"].median()
df["Income"] = df["Income"].fillna(median_income)
print("Missing values before cleaning:", missing_before)
print("Median income used:", median_income)
print("Missing values after cleaning:", df["Income"].isnull().sum())

Missing values before cleaning: 24
Median income used: 51381.5
Missing values after cleaning: 0

In [18]:
print("total missing values:",df.isnull().sum())
print("dataset shape:",df.shape)

total missing values: ID                     0
Year_Birth             0
Education              0
Marital_Status         0
Income                 0
Kidhome                0
Teenhome               0
Dt_Customer            0
Recency                0
MntWines               0
MntFruits              0
MntMeatProducts        0
MntFishProducts        0
MntSweetProducts       0
MntGoldProds           0
NumDealsPurchases      0
NumWebPurchases        0
NumCatalogPurchases    0
NumStorePurchases      0
NumWebVisitsMonth      0
AcceptedCmp3           0
AcceptedCmp4           0
AcceptedCmp5           0
AcceptedCmp1           0
AcceptedCmp2           0
Complain               0
Z_CostContact          0
Z_Revenue              0
Response               0
dtype: int64
dataset shape: (2240, 29)

In [19]:

print("Duplicate rows before removal:", df.duplicated().sum())

df = df.drop_duplicates()
print("Duplicate rows after removal:", df.duplicated().sum())
print("Dataset shape after duplicate removal:", df.shape)

Duplicate rows before removal: 0
Duplicate rows after removal: 0
Dataset shape after duplicate removal: (2240, 29)

In [21]:
print("Before:", df["Dt_Customer"].dtype)
df["Dt_Customer"] = pd.to_datetime(
    df["Dt_Customer"],
    dayfirst=True,
    errors="coerce"
)

print("After:", df["Dt_Customer"].dtype)
print("Invalid dates:", df["Dt_Customer"].isnull().sum())

Before: object
After: datetime64[ns]
Invalid dates: 0

In [22]:

print("Education categories:")
print(df["Education"].value_counts())

print("\nMarital status categories:")
print(df["Marital_Status"].value_counts())

Education categories:
Education
Graduation    1127
PhD            486
Master         370
2n Cycle       203
Basic           54
Name: count, dtype: int64

Marital status categories:
Marital_Status
Married     864
Together    580
Single      480
Divorced    232
Widow        77
Alone         3
Absurd        2
YOLO          2
Name: count, dtype: int64

In [23]:

unusual_status = ["Alone", "Absurd", "YOLO"]

display(
    df[df["Marital_Status"].isin(unusual_status)]
    [["ID", "Year_Birth", "Education", "Marital_Status", "Income"]]
)

         ID  Year_Birth   Education Marital_Status   Income
131     433        1958      Master          Alone  61331.0
138    7660        1973         PhD          Alone  35860.0
153      92        1988  Graduation          Alone  34176.0
2093   7734        1993  Graduation         Absurd  79244.0
2134   4369        1957      Master         Absurd  65487.0
2177    492        1973         PhD           YOLO  48432.0
2202  11133        1973         PhD           YOLO  48432.0

In [24]:

df["Marital_Status"] = df["Marital_Status"].replace({
    "Absurd": "Unknown",
    "YOLO": "Unknown"
})
print(df["Marital_Status"].value_counts())

print("\nRemaining unusual values:")
print(
    df[df["Marital_Status"].isin(["Absurd", "YOLO"])]
    ["Marital_Status"].count()
)

Marital_Status
Married     864
Together    580
Single      480
Divorced    232
Widow        77
Unknown       4
Alone         3
Name: count, dtype: int64

Remaining unusual values:
0

In [25]:

print("Final dataset shape:", df.shape)
print("Total missing values:", df.isnull().sum().sum())
print("Duplicate rows:", df.duplicated().sum())
print("Invalid dates:", df["Dt_Customer"].isnull().sum())
df.to_csv("marketing_campaign_cleaned.csv", index=False)
print("\nCleaned dataset saved successfully!")

Final dataset shape: (2240, 29)
Total missing values: 0
Duplicate rows: 0
Invalid dates: 0

Cleaned dataset saved successfully!

In [26]:

from google.colab import files

files.download("marketing_campaign_cleaned.csv")